### ISSUE TITLE
Error con los SSL

### ISSUE THREAD

**Issue by cz9dev** [oleksis/picta-dl-gui#10]
Me da error con el tema del ssl, es como si la gui no tubiera implementado el --no-check-certificate

**Comment by oleksis** [comment]
La GUI usa `picta-dl` y puedes usar la [configuracion](https://github.com/oleksis/picta-dl#configuration) para que utilize opciones extra. Si los cretificados de tu sistema operativo no estan actualizados (o los del servidor de Picta) puedes usar la opcion `--no-check-certificate` como se explica en el [Workarounds](https://github.com/oleksis/picta-dl#workarounds)

**Comment by cz9dev** [comment]
> La GUI usa `picta-dl` y puedes usar la [configuracion](https://github.com/oleksis/picta-dl#configuration) para que utilize opciones extra. Si los cretificados de tu sistema operativo no estan actualizados (o los del servidor de Picta) puedes usar la opcion `--no-check-certificate` como se explica en el [Workarounds](https://github.com/oleksis/picta-dl#workarounds)

ok eso lo entendí, pero utilizando la GUI no pude, y usando la opción de la GUI de utilizar el archivo de configuración no pude, ¿no tienes algún ejemplo mejor explicado?, el sistema operativo que utilizo es ubuntu por si es util

**Comment by oleksis** [comment]
`Picta-dl_GUI` utiliza el [directorio estandar de la aplicacion](https://github.com/oleksis/picta-dl-gui/blob/07f0e4afe266df55f640395cfab9c1208d408804/mainwindow.cpp#L11) del sistema para almacenar la configuracion de la GUI y de `picta-dl`, al descargar la multimedia utiliza el parametro [`--config-location`](https://github.com/oleksis/picta-dl-gui/blob/07f0e4afe266df55f640395cfab9c1208d408804/mainwindow.cpp#L338)

Segun tu sistema operativo (Ubuntu) y Qt 5.15, el [directorio estandar](https://doc-snapshots.qt.io/qt5-5.15/qstandardpaths.html) en GNU/Linux son los siguientes:

AppDataLocation | "~/.local/share/<APPNAME>", "/usr/local/share/<APPNAME>", "/usr/share/<APPNAME>"
-- | --

Por lo que debes buscar por ejemplo en `~/.local/share/Picta-dl_GUI/picta-dl.conf` la configuracion para `picta-dl` que utiliza la GUI

**Comment by cz9dev** [comment]
@oleksis tal como mencionaste, en la ruta "~/local/share/Picta-dl_GUI/"  no existía el archivo picta-dl.conf, por lo que lo cree con el parámetro `--no-check-certificate` y ya esta funcionando. Voy a cerrar ya que ha sido solucionado el problema
