### ISSUE TITLE
Error de usuario y contraseña

### ISSUE THREAD

**Issue by cccaballero** [oleksis/picta-dl-gui#6]
Usando Ubuntu 20.04 devuelve el mensaje:

```
Las listas de reproducción es sólo para usuarios registrados
Revise su usuario y contraseña.
```

He probado y confirmado que el usuario y contraseña colocado en la configuración es correcto, pero el error continúa.

**Comment by oleksis** [comment]
> ...
> He probado y confirmado que el usuario y contraseña colocado en la configuración es correcto, pero el error continúa.

El usuario y contraseña  que se pone en la configuración es el que te registras en Picta.cu y se utiliza para las listas de reproducción (Playlists) creada por un Usuario ("no públicas")

Podrías ayudar a descartar si es problema de la GUI o no si utilizas la CLI por ejemplo:

```bash
picta-dl -u "USUARIO" -p "CONTRASEÑA" -v [URL]
```
y compartir los Logs.

**Comment by oleksis** [comment]
Hice las pruebas desde el CLI con picta-dl y las listas de reproducción de Usuarios está funcionando!

**Comment by cccaballero** [comment]
> ```shell
> picta-dl -u "USUARIO" -p "CONTRASEÑA" -v [URL]
> ```

Así con el CLI me funciona perfecto

**Comment by Spheres-cu** [comment]
> > ```shell
> > picta-dl -u "USUARIO" -p "CONTRASEÑA" -v [URL]
> > ```
> 
> Así con el CLI me funciona perfecto

Si tienes un fork del proyecto en Ubuntu 20.04 trata de hacer un qDebug() con la salida de los parámetros en el método getfilename, sería algo como: `qDbug() << "Argumentos: "<< arg;` y revisa sí está pasando bien usuario y contraseña

**Comment by Spheres-cu** [comment]
Acabo de hacer las pruebas en un LiveCD de Ubuntu 20.04 LTS descargando una lista personalizada y sin ningún problema con el usuario y contraseña, dejo las capturas de las pruebas.

![Ubuntu_20 04_Picta-dl-GUI](https://user-images.githubusercontent.com/72468068/107286818-1861c580-6a2f-11eb-8310-24ba94506890.png)
![Ubuntu_20 04_Picta-dl-GUI-2](https://user-images.githubusercontent.com/72468068/107286823-1992f280-6a2f-11eb-8021-c2f301d7bc39.png)
![Ubuntu_20 04_Picta-dl-GUI-3](https://user-images.githubusercontent.com/72468068/107286825-1992f280-6a2f-11eb-8605-320be9f2a0ff.png)

Mi consejo es que revise bien las configuraciones que tiene de picta-dl en su PC quizás estén entrando en conflicto con la de la GUI
Cierro este issue  por el momento, cualquier problema se vuelve a abrir uno nuevo.

Saludos
